data_split:
  test_size: 0.2
  random_state: 42

scaling:
  enabled: true

models:
  knn:
    n_neighbors: 5
  rf:
    n_estimators: 100
    random_state: 42

mlflow:
  experiment_name: "Used Car Price Regression Comparison"
